# this will also include kotlin ;)
language: java


# we need to explicitly change to java 8
jdk:
  - oraclejdk8



# avoid re-downloading dependencies all the time
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


script:
- gradle assemble -Dgadsu.skipMacBundle=true
- gradle check -Dgadsu.skipMacBundle=true
# wont get picked up as no wrapper available for this project (yet)
#- ./gradlew assemble -Dgadsu.skipMacBundle=true
#- ./gradlew check -Dgadsu.skipMacBundle=true
